French Translation
auyer/commanderBot pull request #16
Opened 2019-07-28 13:15 UTC by sheldoncoupeheure

untested, not sure about the Go implementation

2019-07-28 16:37 UTC, auyer commented
Thanks for your contribution ! Don't worry about the tests and the implementation, I can do them myself.
There is only one issue that I had forgotten about. There were a couple changes in the develop branch planned for version `1.0`, including a couple new messages.

I just made the necessary changes, and inserted the new fields into your FR translation part (in english).
Can you translate the `SummonHelp` key, and one new line in the `HelpMessage`  ? 
Thanks!

2019-07-28 16:39 UTC, auyer requested changes

2019-07-28 16:39 UTC, auyer commented on public/messages.yaml
> +      \' %s summon\' summon all users connected to voice channels into one.
Can you translate this new line please?

2019-07-28 16:39 UTC, auyer commented on public/messages.yaml
> +    %s
Can you translate this new key please?

2019-07-28 21:00 UTC, auyer commented on public/messages.yaml
>      1 - [EN] Type \' %s lang\' followed by \'EN\' or \'1\' to select the English language
This line needs translation as well.

2019-07-28 21:08 UTC, auyer requested changes

2019-07-28 21:08 UTC, auyer commented on public/messages.yaml
>      1 - [EN] Type \' %s lang\' followed by \'EN\' or \'1\' to select the English language
Almost forgot about this line. It needs translation as well.

2019-07-29 10:31 UTC, sheldoncoupeheure commented
@auyer I think there's nothing left to translate !

2019-07-29 11:41 UTC, auyer approved these changes

2019-07-29 11:41 UTC, merged

2019-07-29 11:42 UTC, auyer commented
Thank you so much ! Merci beaucoup!